<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ITEM-S73641" name="TestCases.TC09_CatalogEng" tests="1" failures="0" timestamp="16 Mar 2021 20:05:29 GMT" time="40.855" errors="1">
  <testcase name="TC09_CatalogEng1" time="40.855" classname="TestCases.TC09_CatalogEng">
    <error type="junit.framework.AssertionFailedError" message="Error while clicking on element :[[ChromeDriver: chrome on XP (cacb5b06d548004529f8097122de2852)] -&gt; id: catalog_save_btn]">
      <![CDATA[junit.framework.AssertionFailedError: Error while clicking on element :[[ChromeDriver: chrome on XP (cacb5b06d548004529f8097122de2852)] -> id: catalog_save_btn]
	at junit.framework.Assert.fail(Assert.java:47)
	at base.BaseTest.click(BaseTest.java:196)
	at PageObjects.Catalog.save_message_validation(Catalog.java:317)
	at TestCases.TC09_CatalogEng.TC09_CatalogEng1(TC09_CatalogEng.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- TC09_CatalogEng1 -->
</testsuite> <!-- TestCases.TC09_CatalogEng -->
